
services:
  app-postgres:
    container_name: app-postgres

    image: postgres:lates
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=adegas-db
      - POSTGRES_USER=adegas
      - POSTGRES_PASSWORD=adegas!40

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "adegas"]
      interval: 30s
      timeout: 30s
      retries: 3

  

  

