// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: add_adegas.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddAdegaService_AddAdega_FullMethodName = "/AddAdegaService/AddAdega"
)

// AddAdegaServiceClient is the client API for AddAdegaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddAdegaServiceClient interface {
	AddAdega(ctx context.Context, in *AdegaRequestBody, opts ...grpc.CallOption) (*AddAdegaResponse, error)
}

type addAdegaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddAdegaServiceClient(cc grpc.ClientConnInterface) AddAdegaServiceClient {
	return &addAdegaServiceClient{cc}
}

func (c *addAdegaServiceClient) AddAdega(ctx context.Context, in *AdegaRequestBody, opts ...grpc.CallOption) (*AddAdegaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAdegaResponse)
	err := c.cc.Invoke(ctx, AddAdegaService_AddAdega_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddAdegaServiceServer is the server API for AddAdegaService service.
// All implementations must embed UnimplementedAddAdegaServiceServer
// for forward compatibility.
type AddAdegaServiceServer interface {
	AddAdega(context.Context, *AdegaRequestBody) (*AddAdegaResponse, error)
	mustEmbedUnimplementedAddAdegaServiceServer()
}

// UnimplementedAddAdegaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddAdegaServiceServer struct{}

func (UnimplementedAddAdegaServiceServer) AddAdega(context.Context, *AdegaRequestBody) (*AddAdegaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAdega not implemented")
}
func (UnimplementedAddAdegaServiceServer) mustEmbedUnimplementedAddAdegaServiceServer() {}
func (UnimplementedAddAdegaServiceServer) testEmbeddedByValue()                         {}

// UnsafeAddAdegaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddAdegaServiceServer will
// result in compilation errors.
type UnsafeAddAdegaServiceServer interface {
	mustEmbedUnimplementedAddAdegaServiceServer()
}

func RegisterAddAdegaServiceServer(s grpc.ServiceRegistrar, srv AddAdegaServiceServer) {
	// If the following call pancis, it indicates UnimplementedAddAdegaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddAdegaService_ServiceDesc, srv)
}

func _AddAdegaService_AddAdega_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdegaRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAdegaServiceServer).AddAdega(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddAdegaService_AddAdega_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAdegaServiceServer).AddAdega(ctx, req.(*AdegaRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

// AddAdegaService_ServiceDesc is the grpc.ServiceDesc for AddAdegaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddAdegaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AddAdegaService",
	HandlerType: (*AddAdegaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAdega",
			Handler:    _AddAdegaService_AddAdega_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add_adegas.proto",
}
